# Theme settings
doks:
    baseurl: https://docs.tokaido.io
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Tokaido
            image: images/logo.svg
        # nav:
        #     - item_name: GitHub
        #       item_url: '#'
        #     - item_name: Item 2
        #       item_url: '#'
        #     - item_name: Item 3
        #       item_url: '#'
    footer:
        content:
            logo:
                text: Tokaido
                image: images/logo.svg
            # copyright: Copyright &copy; 2017. - Project name <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://www.twitter.com/tokaido-io'
            - network_name: github
              profile_url: 'https://www.github.com/tokaido-io'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/tokaido-io'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
